# devgagan
# Note if you are trying to deploy on vps then directly fill values in ("")

from os import getenv

API_ID = int(getenv("API_ID", "25120174"))
API_HASH = getenv("API_HASH", "89a10ea368b634194752731a7c405e30")
BOT_TOKEN = getenv("BOT_TOKEN", "8128468409:AAHtFMzyeRTgVfu6TqHmYbJ-zvnaIVepE6k")
OWNER_ID = list(map(int, getenv("OWNER_ID", "6820248376").split()))
MONGO_DB = getenv("MONGO_DB", "mongodb+srv://venom:cnqHd4qPjRAPdakY@venom.zkis3.mongodb.net/")
LOG_GROUP = getenv("LOG_GROUP", "-1002226652008")
CHANNEL_ID = int(getenv("CHANNEL_ID", "-1002216382990"))
FREEMIUM_LIMIT = int(getenv("FREEMIUM_LIMIT", "0"))
PREMIUM_LIMIT = int(getenv("PREMIUM_LIMIT", "500"))
WEBSITE_URL = getenv("WEBSITE_URL", "upshr")
AD_API = getenv("AD_API", "52b4a2cf4687d8f2b7bc2943f618e78cb")
STRING = getenv("STRING", None)
YT_COOKIES = getenv("YT_COOKIES", None)
INSTA_COOKIES = getenv("INSTA_COOKIES", "# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.instagram.com	TRUE	/	TRUE	1775601265	ps_n	1
#HttpOnly_.instagram.com	TRUE	/	TRUE	1773954451	datr	kg2tZ4mAmm60yqqDrUu7OEhe
.instagram.com	TRUE	/	TRUE	1770930451	ig_nrcb	1
.instagram.com	TRUE	/	TRUE	1748817334	ds_user_id	64271844085
.instagram.com	TRUE	/	TRUE	1772490934	csrftoken	Cxj1OeW0Xg104K0CuEC7c7
#HttpOnly_.instagram.com	TRUE	/	TRUE	1770931877	ig_did	D6D47ADD-FB08-4691-B28E-2A2397957C85
#HttpOnly_.instagram.com	TRUE	/	TRUE	1775601265	ps_l	1
.instagram.com	TRUE	/	TRUE	1741646118	wd	1536x730
.instagram.com	TRUE	/	TRUE	1773954451	mid	Z60NkwALAAEJQVIBG4Mquk3Y9WF3
#HttpOnly_.instagram.com	TRUE	/	TRUE	1772577313	sessionid	64271844085%3APcaBKG20TH4THf%3A29%3AAYe2i01Emv1Jn0L3QtqDWWFwfbZmrCaXOELVl3v5oA
.instagram.com	TRUE	/	TRUE	1741646118	dpr	1.25
#HttpOnly_.instagram.com	TRUE	/	TRUE	1741127736	rur	"RVA\05464271844085\0541772577335:01f7c32bf6b5f3c885b36d13c59964d008394685ebbd7e51e9636283e6c0c6ef53311dab"")
